---
- name: git tasks
  hosts: localhost
  connection: local 
  become: false 

  vars:
     git_dir:  /home/cstockman/git

  tasks:
  - name: setup Editor Value 
    git_config:
      name: core.editor
      scope: global
      value: "{{ lookup('env', 'config_textEditor') }}" 

  - name: setup Username Value
    git_config:
      name: user.name
      scope: global 
      value: "{{ lookup('env', 'config_fullName') }}" 

  - name: setup email
    git_config:
      name: user.email
      scope: global
      value: "{{ lookup('env', 'config_email')  }}" 
